### ISSUE TITLE
TypeError: 'Polygon' object is not iterable

### ISSUE THREAD

**Issue by Goschjann** [NikolayOskolkov/tSNE_vs_UMAP_GlobalStructure#1]
Hi Nikolay, 

thanks for the great blogpost on tSNE/ Umap and their specialties. 

For a university seminar, I would like to let the students play around with the great World Dataset that you generated for your blog post and reference here within this repository (giving you author credits of course). 

Unfortunately, I keep running in the following error when trying to run your code:

```
Traceback (most recent call last):
  File "world.py", line 22, in <module>
    label=country.attributes['NAME_LONG'], color = 'black')
  File "/home/ubuntu/miniconda3/envs/world/lib/python3.6/site-packages/cartopy/mpl/geoaxes.py", line 718, in add_geometries
    feature = cartopy.feature.ShapelyFeature(geoms, crs, **kwargs)
  File "/home/ubuntu/miniconda3/envs/world/lib/python3.6/site-packages/cartopy/feature/__init__.py", line 221, in __init__
    self._geoms = tuple(geometries)
TypeError: 'Polygon' object is not iterable
```
Are you aware of this issue and do you maybe even have a solution? 

Thanks in advance!

**Comment by Goschjann** [comment]
Update @NikolayOskolkov 

some of the `country.geometries()` come as `Polygons` instead of `Multipolygons`, causing above error. 

A simple try-catch inputting the `Polygon` geoms as a list does the trick:

```
        try:
            ax.add_geometries(country.geometry, ccrs.Miller(), label=country.attributes['NAME_LONG'], color = 'black')
        except:
            ax.add_geometries([country.geometry], ccrs.Miller(), label=country.attributes['NAME_LONG'], color = 'black')
```

Thanks for the blog post anyways!

Will close this issue

**Comment by Goschjann** [comment]
One thing to add:

you should comment the lines `ax.set_extent([-180, 180, -50, 70])` as these do not seem to fit anymore with some later `cartopy` update

**Comment by NikolayOskolkov** [comment]
Hi @Goschjann, thanks a lot for figuring out the fix for the issue with data generation, it worked fine for me without errors so I was not aware of the issue. Yes, perfectly fine to use the data set for the seminar, good luck!
